# Generated by Django 6.1 on 2026-09-09 11:30

import django.core.validators
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.Sh.')),
                ('username', models.CharField(blank=True, help_text='Ixtiyoriy. Login uchun emas — login telefon raqam orqali.', max_length=150, null=True, unique=True, verbose_name='Username')),
                ('phone_number', models.CharField(help_text='+998901234567 formatida.', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('admin', 'Administrator')], default='user', max_length=10, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=False, help_text="Telegram bot orqali kod tasdiqlangandan keyin True bo'ladi.", verbose_name='Faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Xodim (admin panel)')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, help_text='Botga /start bosganda yoziladi.', null=True, verbose_name='Telegram ID')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi kirish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('purpose', models.CharField(choices=[('register', "Ro'yxatdan o'tish"), ('reset_password', 'Parolni tiklash')], default='register', max_length=20, verbose_name='Maqsad')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Urinishlar soni')),
                ('expires_at', models.DateTimeField(default=users.models.default_expires_at, verbose_name='Amal qilish muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tasdiqlash kodi',
                'verbose_name_plural': 'Tasdiqlash kodlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_user_role_e1ec1a_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='users_verif_user_id_131aa1_idx'),
        ),
    ]
