# Generated by Django 6.1 on 2026-09-09 12:03

import users.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=users.utils.PhoneNumberField(help_text="901112233, 998901112233 yoki +998 90 111 22 33 — bazada +998901112233 ko'rinishida saqlanadi.", unique=True, verbose_name='Telefon raqam'),
        ),
    ]
